# Generated by Django 3.1.6 on 2021-02-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
    ]
